// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpmbafhpbeupqktftlux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbWJhZmhwYmV1cHFrdGZ0bHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDMwMTAsImV4cCI6MjA2NjMxOTAxMH0.HuptsRE1SkBLSZCH6s97bZeBIzVUVQvEfSi87ptEk5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);